### ISSUE TITLE
Chrome and Safari can't click and drag their scrollbar.

### ISSUE THREAD

**Issue by Nightfirecat** [atomizer/fitting#10]
When accessing fitting room on Chrome or Safari, they can only scroll using other methods - they cannot click and drag their scrollbar to adjust the page.

As far as I've been able to tell, [this is some kind of Webkit-specific bug after the new scrollbars were introduced](https://code.google.com/p/chromium/issues/detail?id=334522). It was (supposedly) fixed in a recent release, but still seems to be apparent on fitting room, and there's no clear reason why.

I'll look into possible causes later this week, but I just wanted to bring this up since a couple people informed me it was an issue.

**Comment by atomizer** [comment]
Yes, this is a browser bug. The cause is that we disable default action for
mousedown to prevent accidental text selection ugliness. It is not supposed
to affect browser frame. Better wait for the fix to propagate IMO.

**Comment by Nightfirecat** [comment]
Ah, makes sense.

Probably best to just wait until they figure out this mess then.

**Comment by atomizer** [comment]
Looks fixed to me.

**Comment by Nightfirecat** [comment]
It still appears to be an issue on my end using Chrome 36.0.1985.125m (public release).

**Comment by atomizer** [comment]
Yes, [the fix](https://code.google.com/p/chromium/issues/detail?id=369898#c11) was merged somewhere in 37, so it will be in stable eventually (should be not long from now).

**Comment by Nightfirecat** [comment]
Neat. Just wanted to check on that.
