### ISSUE TITLE
New Event Skins Missing

### ISSUE THREAD

**Issue by Nightfirecat** [atomizer/fitting#14]
It seems that the skins from the Puppet Master, Halloween, Tinkerer, Alchemist are missing. Below should be a comprehensive list of all of the missing skins.
- Rogue - Jack the Ripper ![jack the ripper rogue skin](http://static.drips.pw/rotmg/wiki/Skins/Jack%20the%20Ripper.png)
- Archer - Huntsman ![huntsman archer skin](http://static.drips.pw/rotmg/wiki/Skins/Huntsman.png)
- Wizard - Mischievous Imp ![mischievous imp wizard skin](http://static.drips.pw/rotmg/wiki/Skins/Mischievous%20Imp.png)
- Priest - Zombie Nurse ![zombie nurse priest skin](http://static.drips.pw/rotmg/wiki/Skins/Zombie%20Nurse.png)
- Warrior - Skeleton Warrior ![skeleton warrior warrior skin](http://static.drips.pw/rotmg/wiki/Skins/Skeleton%20Warrior.png)
- Warrior - Hunchback ![hunchback warrior skin](http://static.drips.pw/rotmg/wiki/Skins/Hunchback.png)
- Knight - Frankenstein's Monster ![frankenstein's monster knight skin](http://static.drips.pw/rotmg/wiki/Skins/Frankenstein%27s%20Monster.png)
- Paladin - Demon Spawn ![demon spawn paladin skin](http://static.drips.pw/rotmg/wiki/Skins/Demon%20Spawn.png)
- Assassin - Puppet Master ![puppet master assassin skin](http://static.drips.pw/rotmg/wiki/Skins/Puppet%20Master.png)
- Assassin - Infected Assassin ![infected assassin assassin skin](http://static.drips.pw/rotmg/wiki/Skins/Infected%20Assassin.png)
- Assassin - Vampire Hunter ![vampire hunter assassin skin](http://static.drips.pw/rotmg/wiki/Skins/Vampire%20Hunter.png)
- Necromancer - Tiny Avatar ![tiny avatar necromancer skin](http://static.drips.pw/rotmg/wiki/Skins/Tiny%20Avatar.png)
- Huntress - Ghost Huntress ![ghost huntress huntress skin](http://static.drips.pw/rotmg/wiki/Skins/Ghost%20Huntress.png)
- Huntress - Dark Elf Huntress ![dark elf huntress huntress skin](http://static.drips.pw/rotmg/wiki/Skins/Dark%20Elf%20Huntress.png)
- Mystic - Poltergeist ![poltergeist mystic skin](http://static.drips.pw/rotmg/wiki/Skins/Poltergeist.png)
- Trickster - Jester ![jester trickster skin](http://static.drips.pw/rotmg/wiki/Skins/Jester.png)
- Trickster - Vampiress ![vampiress trickster skin](http://static.drips.pw/rotmg/wiki/Skins/Vampiress.png)
- Sorcerer - Ascended Sorcerer ![ascended sorcerer sorcerer skin](http://static.drips.pw/rotmg/wiki/Skins/Ascended%20Sorcerer.png)
- Ninja - Death ![death ninja skin](http://static.drips.pw/rotmg/wiki/Skins/Death.png)

(sourced from [the character skins wiki page](https://www.realmeye.com/wiki/character-skins))

**Comment by Huffines** [comment]
I noticed this issue also, and it annoyed me due to the fact my favorite skin was a halloween one, and I could not check what it could look like with a dye.
